### ISSUE TITLE
Reporting Error

### ISSUE THREAD

**Issue by pchandu587** [JWock82/PyNite#62]
When i execute Simple Beam - Point Load.py  file. This error came. How to resolve this issue.

I```
NFO: Could not find files for the given pattern(s).
Traceback (most recent call last):
  File "C:\Users\cparlapalle\AppData\Local\Programs\Python\Python38\lib\site-packages\pdfkit\configuration.py", line 21, in __init__
    with open(self.wkhtmltopdf) as f:
FileNotFoundError: [Errno 2] No such file or directory: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/pynitefem/simplebeam_pointload.py", line 60, in <module>
    Reporting.CreateReport(SimpleBeam, output_filepath='.//PyNite Report.pdf', plates=False, plate_corner_forces=False, \
  File "E:\pynitefem\PyNite\Reporting.py", line 36, in CreateReport
    pdfkit.from_string(HTML, output_filepath, css='.//PyNite//MainStyleSheet.css')
  File "C:\Users\cparlapalle\AppData\Local\Programs\Python\Python38\lib\site-packages\pdfkit\api.py", line 69, in from_string
    r = PDFKit(input, 'string', options=options, toc=toc, cover=cover, css=css,
  File "C:\Users\cparlapalle\AppData\Local\Programs\Python\Python38\lib\site-packages\pdfkit\pdfkit.py", line 42, in __init__
    self.configuration = (Configuration() if configuration is None
  File "C:\Users\cparlapalle\AppData\Local\Programs\Python\Python38\lib\site-packages\pdfkit\configuration.py", line 24, in __init__
    raise IOError('No wkhtmltopdf executable found: "%s"\n'
OSError: No wkhtmltopdf executable found: "b''"
If this file exists please check that this process can read it. Otherwise please install wkhtmltopdf - https://github.com/JazzCore/python-pdfkit/wiki/Installing-wkhtmltopdf

Process finished with exit code 1

```

**Comment by JWock82** [comment]
I recently updated this example to include PDF reporting. If you're not interested in the PDF report, you can just comment out the last group of lines at the end of the file related to PDF reporting. If you are interested in the PDF reporting features, you'll need to follow the instructions on generating reports in the wiki of this repository.

**Comment by JWock82** [comment]
Can you confirm if this solved your problem? I'd like to close this issue out.
